#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Generate the codepoint-width tables used by fyts.c:
#
#   src/fyts-wcwidth-zero.h  - zero_width_ranges[]: codepoints that occupy no
#                              terminal column (combining and zero-width format
#                              marks).
#   src/fyts-wcwidth-wide.h  - wide_ranges[]: codepoints that occupy two columns
#                              (East Asian Wide/Fullwidth and emoji).
#
# Both are emitted as C {lo,hi} CpRange initializer lists, #included into the
# array bodies in src/fyts.c. Derived from the Python build's Unicode database,
# so regenerate after a Unicode bump:
#
#     python3 scripts/gen-wcwidth.py

import os
import sys
import unicodedata as u

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.normpath(os.path.join(HERE, "..", "src"))

# Base set: nonspacing (Mn) and enclosing (Me) marks. Spacing combining marks
# (Mc) are deliberately excluded; they advance the cursor one column.
ZERO_WIDTH_FORMAT = [
    (0x00AD, 0x00AD),    # SOFT HYPHEN
    (0x180E, 0x180E),    # MONGOLIAN VOWEL SEPARATOR
    (0x200B, 0x200F),    # ZERO WIDTH SPACE .. RIGHT-TO-LEFT MARK
    (0x202A, 0x202E),    # bidi embedding/override controls
    (0x2060, 0x2064),    # WORD JOINER .. INVISIBLE PLUS
    (0x2066, 0x206F),    # bidi isolates and deprecated format controls
    (0xFEFF, 0xFEFF),    # ZERO WIDTH NO-BREAK SPACE (BOM)
    (0xFFF9, 0xFFFB),    # interlinear annotation controls
    (0x110BD, 0x110BD),  # KAITHI NUMBER SIGN
    (0x110CD, 0x110CD),  # KAITHI NUMBER SIGN ABOVE
    (0x13430, 0x1343F),  # Egyptian Hieroglyph format controls
    (0x1BCA0, 0x1BCA3),  # Shorthand Format Controls
    (0x1D173, 0x1D17A),  # MUSICAL SYMBOL BEGIN BEAM .. END PHRASE
    (0xE0001, 0xE0001),  # LANGUAGE TAG
    (0xE0020, 0xE007F),  # TAG SPACE .. CANCEL TAG
]

# Emoji_Presentation=Yes ranges whose East Asian Width is not W/F. unicodedata
# does not expose Emoji_Presentation, so these are listed explicitly.
EMOJI_PRESENTATION_EXTRA = [
    (0x03248, 0x0324F),  # circled numbers on black squares
    (0x1F1E6, 0x1F1FF),  # regional indicator symbols (flags)
    (0x1F93B, 0x1F93B),  # modern pentathlon
    (0x1F946, 0x1F946),  # rifle
    (0x1FA60, 0x1FA6D),  # xiangqi pieces
]


def zero_width_codepoints():
    cps = set(cp for cp in range(0x110000)
              if not (0xD800 <= cp <= 0xDFFF)
              and u.category(chr(cp)) in ("Mn", "Me"))
    for lo, hi in ZERO_WIDTH_FORMAT:
        cps.update(range(lo, hi + 1))
    return cps


def wide_codepoints():
    cps = set(cp for cp in range(0x110000)
              if not (0xD800 <= cp <= 0xDFFF)
              and u.east_asian_width(chr(cp)) in ("W", "F"))
    for lo, hi in EMOJI_PRESENTATION_EXTRA:
        cps.update(range(lo, hi + 1))
    return cps


def to_ranges(cps):
    ranges = []
    it = sorted(cps)
    start = prev = it[0]
    for cp in it[1:]:
        if cp == prev + 1:
            prev = cp
        else:
            ranges.append((start, prev))
            start = prev = cp
    ranges.append((start, prev))
    return ranges


def emit(path, array, ranges):
    with open(path, "w") as f:
        f.write("/* %s: generated by scripts/gen-wcwidth.py from Unicode %s. */\n"
                "/* Do not edit by hand; rerun the script after a Unicode bump. */\n"
                % (array, u.unidata_version))
        for i in range(0, len(ranges), 4):
            chunk = ranges[i:i + 4]
            f.write("\t" + ",".join("{0x%x,0x%x}" % (a, b) for a, b in chunk)
                    + ("," if i + 4 < len(ranges) else "") + "\n")
    print("wrote %s (%d ranges)" % (path, len(ranges)), file=sys.stderr)


def main():
    emit(os.path.join(SRC, "fyts-wcwidth-zero.h"),
         "zero_width_ranges[]", to_ranges(zero_width_codepoints()))
    emit(os.path.join(SRC, "fyts-wcwidth-wide.h"),
         "wide_ranges[]", to_ranges(wide_codepoints()))


if __name__ == "__main__":
    main()
