#!/usr/bin/env python3
#
# Convert a local folke/tokyonight.nvim checkout into a fyts styling file.

import argparse
import re
import sys
from pathlib import Path


HEX_RE = re.compile(r'([A-Za-z_][A-Za-z0-9_]*)\s*=\s*["\'](#[0-9A-Fa-f]{6})["\']')
REQUIRE_RE = re.compile(r'require\(["\']tokyonight\.colors\.([A-Za-z0-9_-]+)["\']\)')


CAPTURES = [
    (r"^diff\.plus$", "diff-added"),
    (r"^diff\.minus$", "diff-removed"),
    (r"^string\.special\.path$", "path"),
    (r"^string\.special\.key$", "key"),
    (r"^escape$", "escape"),
    (r"^embedded$", "embedded"),
    (r"^attribute$", "attribute"),
    (r"^label$", "label"),
    (r"^property$", "property"),
    (r"^boolean$", "constant"),
    (r"^comment$", "comment"),
    (r"^string$", "string"),
    (r"^number$", "constant"),
    (r"^constant(\..*)?$", "constant"),
    (r"^keyword$", "keyword"),
    (r"^conditional$", "control"),
    (r"^repeat$", "control"),
    (r"^function(\..*)?$", "function"),
    (r"^method$", "function"),
    (r"^module$", "type"),
    (r"^type$", "type"),
    (r"^class$", "type"),
    (r"^constructor$", "type"),
    (r"^variable(\..*)?$", "variable"),
    (r"^parameter$", "variable"),
    (r"^operator$", "operator"),
    (r"^delimiter$", "punctuation"),
    (r"^punctuation(\..*)?$", "punctuation"),
    (r"^spell$", "text"),
]


ATTRIBUTES = {
    "diff-added": ("green1", "green", "teal"),
    "diff-removed": ("red", "red1"),
    "path": ("yellow", "orange"),
    "key": ("cyan", "blue5", "blue1"),
    "escape": ("orange", "yellow"),
    "embedded": ("fg_dark", "fg"),
    "attribute": ("blue5", "cyan"),
    "label": ("magenta", "purple"),
    "property": ("cyan", "blue5", "blue1"),
    "constant": ("orange", "magenta", "purple"),
    "comment": ("comment", "dark5"),
    "string": ("green", "green1"),
    "keyword": ("magenta", "purple"),
    "control": ("purple", "magenta"),
    "function": ("blue", "cyan"),
    "type": ("yellow", "orange"),
    "variable": ("fg", "fg_dark"),
    "operator": ("blue5", "fg_dark", "fg"),
    "punctuation": ("fg_dark", "fg"),
    "text": ("fg", "fg_dark"),
}


def strip_lua_comments(text):
    lines = []

    for line in text.splitlines():
        quoted = False
        escaped = False
        for index, char in enumerate(line):
            if escaped:
                escaped = False
                continue
            if char == "\\":
                escaped = True
                continue
            if char in ("'", '"'):
                quoted = not quoted
                continue
            if not quoted and line[index:index + 2] == "--":
                line = line[:index]
                break
        lines.append(line)
    return "\n".join(lines)


def palette_path(repo, variant):
    return repo / "lua" / "tokyonight" / "colors" / ("%s.lua" % variant)


def parse_palette(repo, variant, seen=None):
    path = palette_path(repo, variant)
    text = None
    colors = {}
    parent = None

    if seen is None:
        seen = set()
    if variant in seen:
        raise ValueError("recursive palette inheritance at %s" % variant)
    seen.add(variant)

    if not path.exists():
        raise FileNotFoundError("missing palette: %s" % path)

    text = strip_lua_comments(path.read_text(encoding="utf-8"))
    match = REQUIRE_RE.search(text)
    if match:
        parent = match.group(1)
        colors.update(parse_palette(repo, parent, seen))

    for name, value in HEX_RE.findall(text):
        colors[name] = value.lower()

    if not colors:
        raise ValueError(
            "palette %s does not contain static hex colors; choose a static variant such as storm, moon, or night"
            % path
        )
    return colors


def pick(palette, names):
    for name in names:
        if name in palette:
            return name
    raise ValueError("palette is missing all of: %s" % ", ".join(names))


def style_name(variant, color):
    return "tokyonight-%s-%s" % (variant, color)


def sgr(hex_color):
    value = hex_color.lstrip("#")
    red = int(value[0:2], 16)
    green = int(value[2:4], 16)
    blue = int(value[4:6], 16)

    return r"\e[38;2;%d;%d;%dm" % (red, green, blue)


def bg_sgr(hex_color):
    value = hex_color.lstrip("#")
    red = int(value[0:2], 16)
    green = int(value[2:4], 16)
    blue = int(value[4:6], 16)

    return r"\e[48;2;%d;%d;%dm" % (red, green, blue)


def yaml_escape_quote(text):
    return '"' + text.replace('"', '\\"') + '"'


def generate(repo, dark_variant, light_variant):
    dark = parse_palette(repo, dark_variant)
    light = parse_palette(repo, light_variant)
    used = {}
    lines = []

    lines.append("# Generated by scripts/import-tokyonight.py from folke/tokyonight.nvim")
    lines.append("captures:")
    lines.append("  # Capture attributes are matched as POSIX extended regular expressions in order.")
    for capture, attribute in CAPTURES:
        lines.append("  - capture: %s" % capture)
        lines.append("    attribute: %s" % attribute)

    lines.append("")
    lines.append("attributes:")
    for attribute, candidates in ATTRIBUTES.items():
        dark_color = pick(dark, candidates)
        light_color = pick(light, candidates)
        dark_style = style_name(dark_variant, dark_color)
        light_style = style_name(light_variant, light_color)

        used[dark_style] = dark[dark_color]
        used[light_style] = light[light_color]
        lines.append("  %s:" % attribute)
        lines.append("    dark: %s" % dark_style)
        lines.append("    light: %s" % light_style)

    lines.append("")
    lines.append("frame:")
    lines.append("  dark-background: frame-dark-background")
    lines.append("  light-background: frame-light-background")
    lines.append("  dark-conflicts: []")
    lines.append("  light-conflicts: []")
    lines.append("  dark-contrast: frame-dark-contrast")
    lines.append("  light-contrast: frame-light-contrast")
    used["frame-dark-background"] = "#000000"
    used["frame-light-background"] = "#ffffff"
    used["frame-dark-contrast"] = "#ffffff"
    used["frame-light-contrast"] = "#000000"

    lines.append("")
    lines.append("styles:")
    for name in sorted(used):
        escape = bg_sgr(used[name]) if name.endswith("-background") else sgr(used[name])
        lines.append("  %s: %s" % (name, yaml_escape_quote(escape)))
    lines.append("")
    return "\n".join(lines)


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Import a folke/tokyonight.nvim palette as a fyts styling YAML file."
    )
    parser.add_argument(
        "--repo",
        required=True,
        help="path to a local tokyonight.nvim checkout",
    )
    parser.add_argument(
        "--variant",
        default="night",
        help="dark TokyoNight variant to import (default: night)",
    )
    parser.add_argument(
        "--light-variant",
        default="moon",
        help="light-side palette to import (default: moon; use a static palette file)",
    )
    parser.add_argument(
        "--output",
        default="-",
        help="output styling path, or '-' for stdout (default: stdout)",
    )
    return parser.parse_args(argv)


def main(argv):
    args = parse_args(argv)
    repo = Path(args.repo)
    output = None
    text = None

    if not repo.exists():
        print("theme checkout does not exist: %s" % repo, file=sys.stderr)
        return 1

    try:
        text = generate(repo, args.variant, args.light_variant)
    except (OSError, ValueError) as error:
        print("import-tokyonight: %s" % error, file=sys.stderr)
        return 1

    if args.output == "-":
        sys.stdout.write(text)
        return 0

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
